package com.degetel.pmex.en.enums;

public enum RefSetupAlertType {
	WHEN_SHARE_PRICE_IS_OVER,
	WHEN_SHARE_PRICE_IS_UNDER,
	WHEN_SHARES_NUMBERS_ARE_OVER,
	WHEN_SHARES_NUMBERS_ARE_UNDER,
	WHEN_TRANSACTIONS_ARE_OVER,
	WHEN_TRANSACTIONS_ARE_UNDER;
}
